name: CI
on:
  pull_request:
  workflow_dispatch:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Confirm black formatter was ran
        run: |
          pip install black
          black --check .
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Perform pytest against code
        run: |
          pip install pytest boto3 moto
          pip install ./
          pytest
